version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes_app
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - .:/var/www
    networks:
      - app_network
    depends_on:
      - vite
      - db
      
  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    container_name: notes_vite
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app_network

  db:
    image: mysql:latest
    container_name: notes_db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network

  nginx:
    container_name: notes_nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - app_network
    depends_on:
      - app
networks:
  app_network:

volumes:
  db_data: